name: 音乐模板
description: 动态分享网易云音乐
title: "音乐分享 "
labels: ["动态", "音乐"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        请填写音乐信息
  - type: input
    id: contact1
    attributes:
      label: 音乐ID
      description: 输入网易云音乐某首歌的ID，例如https://music.163.com/#/search/m/?s=255294
      placeholder: ex. 255294
    validations:
      required: true
  - type: input
    id: contact2
    attributes:
      label: 音乐名称
      description: 输入网易云音乐某首歌的歌名
      placeholder: ex. 我很快乐
    validations:
      required: true
 - type: input
    id: contact3
    attributes:
      label: 歌手
      description: 输入网易云音乐某首歌的歌手
      placeholder: ex. 刘惜君
    validations:
      required: true
